#!/bin/bash

#To check if we are read write:
touch /testro
status=$?

if [[ "$status" != 0 ]] ; then
	#We are read-only
	mount -o remount,rw /
	/tmp/remountrw
fi
#else nothing to do, we are already rw
