#!/bin/bash
#
# Copyright (c) 2016 Laurent HUBERT, lau.hub@gma**.com
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

. /lib/lsb/init-functions

#To check if we are read write:
touch /testro > /dev/null 2>&1 
status=$?

if [[ "$status" == 0 ]] ; then
	log_action_msg "Remounting filesystems in Read-Only mode"
	#We are read-write
	rm /testro
	mount -o remount,ro /
	/tmp/remountro
else
	log_action_msg "All filesystems are already in Read-Only mode"
fi
#else nothing to do, we are already ro
